### PR TITLE
more conflict resolution

### PR DESCRIPTION
**Pull request by camerond**
Not 100% sure what happened here, but rebased your changes against mine to get my fork back in line, and ended up with duplicate commits? Or perhaps they'll just merge in nicely. In any case, the relevant fixes here are to the homepage and the rest is artifacts from rebasing.

### CODE REVIEW

**Comment by shaneriley** [comment]
Let's see if GitHub will merge it without issue. I had to do some manual merging last time.

**Comment by shaneriley** [comment]
Well, something's still wrong. The width on the section (880px) is fixed, so even though everything else is scaling down when you adjust the browser dimensions, the parent container is a fixed width. Maybe some max-width instead?

**Comment by camerond** [comment]
No idea why that isn't merging right. Compare to https://github.com/camerond/super_number/blob/master/source/stylesheets/application.css.sass which is completely different.

**Comment by shaneriley** [comment]
I manually added your Sass from that file, updated the gems, and set asset path compilation to relative. Just to be certain, before doing anything else on this blow away your local repo and clone again from mine.

**Pull request merged**
